master-branch changes (to scripts) added to molAddAtom branch.

diff --git a/contrib/bd_flex-msub.in b/contrib/bd_flex-msub.in
--- a/contrib/bd_flex-msub.in
+++ b/contrib/bd_flex-msub.in
@@ -21,6 +21,9 @@
 # 
 #msub="/opt/moab/bin/msub -l nodes=1:ppn=10:gpus=2 -V -S /bin/bash"
 #msub="ssh judge /opt/moab/bin/msub -l nodes=1:ppn=10:gpus=2 -V -S /bin/bash"
+nnodes=2
+ncores=24
+msub="ssh judge /opt/moab/bin/msub -l nodes=$nnodes:ppn=$ncores -M valiska@gmail.com -m abe -V -S /bin/bash"
 msub="bash"
 
 # my dear self
@@ -42,8 +45,9 @@ function usage()
   echo "  -B BD_FLEX              use BD_FLEX binary."
   echo "  -i FILE                 input parameter file."
   echo "  -c COUNT                continue (count to keep track on reruns)."
+  echo "  -o \"OPTS\"               pass bd_flex options to the runner."
   echo "  -p NUM                  number of processes (for OpenMP)."
-  echo "  -M PROC,COL,ROW,BLOCK   number of processes, collons, rows and blocks for MPI."
+  echo "  -M MPIPROCS             number of MPI processes."
 
   echo
   echo "  -v                      print version information and exit."
@@ -55,37 +59,42 @@ function usage()
 #
 # Options
 #
-while getopts "d:B:i:p:M:c:v?:" Option
+while getopts "d:B:i:p:M:c:o:v?:" Option
 do
   case $Option in
 
     d  ) directory="$OPTARG"
          cmd="${cmd} -d $OPTARG";;
 
-    B  ) bdflex="$OPTARG"
-         cmd="${cmd} -B $OPTARG";;
+    B  ) cmd="${cmd} -B $OPTARG";;
 
     i  ) input="$OPTARG"
          cmd="${cmd} -i $OPTARG";;
 
-    p  ) nproc="$OPTARG"
-         cmd="${cmd} -p $OPTARG";;
+    p  ) cmd="${cmd} -p $OPTARG";;
 
-    M  ) mpiopt="$OPTARG"
-         cmd="${cmd} -M $OPTARG";;
+    M  )
+  	mpiproc="$OPTARG"
+	mpiproc2=$(echo "$nnodes * $ncores" | bc -l)
+	if test "$mpiproc" != "$mpiproc2"; then
+		echo "$myname: error: thetotal number of MPI procs ($mpiproc) != nnodes x ncores = $nnodes x $ncores = $mpiproc2"
+		exit 1
+	fi
+    	cmd="${cmd} -M $OPTARG";;
 
     c  ) count="$OPTARG"
          cmd="${cmd} -c $OPTARG";;
 
-    r  ) script="$OPTARG"
-         cmd="${cmd} -k $OPTARG";;
+    o  ) cmd="${cmd} -o \"$OPTARG\"";;
+
+    # FIXME: check if we really need this option
+    r  ) cmd="${cmd} -r $OPTARG";;
 
     :  ) echo "$myname: option -$OPTARG requires an argument." >&2
          exit 1 ;;
 
     v  ) echo "$myname from @PACKAGE@ @VERSION@"
          exit 0;;
-
     
     '?'  |  h) usage ${myname}
 	   exit $OPTERROR;;
@@ -99,6 +108,10 @@ shift $(($OPTIND - 1))
 # Check if already queued
 if test -f "$directory/@QUEUE@"; then
 	echo "$myname: error: job is queued already; if this is not the case, remove '$directory/@QUEUE@' and run again."
+	exit 1;
+fi
+if test -f "$directory/@RUNNING@"; then
+	echo "$myname: error: job seems to be running; if this is not the case, remove '$directory/@RUNNING@' and run again."
 	exit 1;
 fi
 
diff --git a/scripts/bdbox-xyz.in b/scripts/bdbox-xyz.in
--- a/scripts/bdbox-xyz.in
+++ b/scripts/bdbox-xyz.in
@@ -89,7 +89,8 @@ function scan_directory ()
 	
 	local dirs=
 	if test -d $dir; then
-		dirs=$(ls $dir)
+#		dirs=$(ls $dir)
+		dirs=$(find $dir/* -type d)
 	fi
 
 	for d in $dirs; do
@@ -101,10 +102,12 @@ function scan_directory ()
 	xyzfiles=$(ls $dir | grep .xyz)
 	for f in $xyzfiles; do
 
+		mkdir -p $dir/moldat
+
 		xyz_mod=$(stat -c %Y $dir/$f)
 		echo "mols=$mols"
 		for imol in $mols; do
-			ofile=$dir/$(basename $f .xyz).mol$imol
+			ofile=$dir/moldat/$(basename $f .xyz).mol$imol
 			redo="yes"
 			if test -f $ofile.dat; then
 			 	dat_mod=$(stat -c %Y $ofile.dat)
@@ -113,19 +116,16 @@ function scan_directory ()
 				fi
 			fi
 
-			 if test "$redo" == "yes" -o "x$overwrite" == "xyes"; then
+			if test "$redo" == "yes" -o "x$overwrite" == "xyes"; then
 		 		echo "Extracting data from '$dir/$f' to $ofile.dat"
 				echo "$analysexyz $analysexyz_opt -f $dir/$f -k$imol"
 				echo "$analysexyz $analysexyz_opt -f $dir/$f -k$imol" > $ofile.cmd
 				$analysexyz $analysexyz_opt -f $dir/$f -k$imol > $ofile.dat
-			 else
-		 		echo "File '$ofile.dat' is up to date, skipping"
-			 fi	
-			if test -z "$files"; then
-				files=$ofile.dat
 			else
-				files="$files,$ofile.dat"
-			fi
+		 		echo "File '$ofile.dat' is up to date, skipping"
+			fi	
+			files="$files $ofile.dat"
+			nfiles=$[$nfiles+1]
 		done
 	done
 }
@@ -203,12 +203,22 @@ if test ! -d "$directory"; then
 	exit 1;
 fi
 
+nfiles=0
 cd $directory && scan_directory .
+
+files_file=`mktemp $myname-XXXXXX`
+if test -n "$files_file"; then
+    echo $files > $files_file
+    average_files=" -F $files_file"
+else
+    echo "$myname: cannot create a temporary file, sorry, I am giving up..."
+    exit 1
+fi
 
 echo
 echo "Avereging:"
-echo $average -f $files -k 0,5 $window
-$average -f $files -k 0,5 $window > $output
+echo $average $average_files -k 0,5 $window
+$average $average_files -k 0,5 $window > $output
 echo "Avereging done."
 
 if test "z$dofit" = "zyes"; then
@@ -224,6 +234,10 @@ if test "z$dofit" = "zyes"; then
 	D=`$fitter -f $output -x1 -y2 -l $fitps $fitinterval`
 	echo "$eta	$D"
 	echo "Fitting done."
+fi
+
+if test -f "$files_file"; then
+	rm $files_file
 fi
 
 exit 0;
